#!/usr/bin/python3
"""
================================
module that returns the list of
available attributes and methods
of an object
================================
"""


def lookup(obj):
    """return the object dir"""
    return dir(obj)

